In [ ]:
# Create a 1D NumPy array named temperatures_w1 for Week 1 with the
# following values:
# [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
import numpy as np
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)



[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [ ]:
# Inspect the shape, data type, and the number of elements in the array.
# Inspect the shape of the temperatures_w1 array.
print('Shape:')
print(temperatures_w1.shape)
print('Data Type:')
print(temperatures_w1.dtype)
print('Size:')
print(temperatures_w1.size)


Shape:
(7,)
Data Type:
float64
Size:
7


In [ ]:
# ● Convert the temperatures_w1 from Celsius to Fahrenheit using the
# formula: Fahrenheit = (Celsius * 9/5) + 32
# ● Find the maximum, minimum, and mean temperatures for the week.

Fahrenheit = (temperatures_w1 * 9/5) + 32
print(Fahrenheit)
print('maximum:')
print(np.max(temperatures_w1))
print('minimum:')
print(np.min(temperatures_w1))
print('mean:')
print(np.mean(temperatures_w1))



[72.5  77.54 69.44 74.12 78.98 76.64 71.42]
maximum:
26.1
minimum:
20.8
mean:
23.542857142857144


In [ ]:
# ● Extract the temperatures for the first three days of the week.
# ● Extract the temperatures for the weekend (last two days).
# ● Extract the temperatures for the middle three days of the week.
print('Extract-the first three days of the week:')
print(temperatures_w1[:3])
print('Extract-last two days ')
print(temperatures_w1[-2:])
print('Extract-middle three days:')
print(temperatures_w1[2:5])

Extract-the first three days of the week:
[22.5 25.3 20.8]
Extract-last two days 
[24.8 21.9]
Extract-middle three days:
[20.8 23.4 26.1]


In [ ]:
# Create a 2D NumPy array named temperatures where each row represents
# temperatures for a different week:
# ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)
# ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)
temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])
print(temperatures)


[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [ ]:
# ● Inspect and print the shape, data type, and total number of elements in the
# temperatures array.
# ● Extract the temperatures for each week and the weekends (last two days)
# for both weeks.
print('Shape:')
print(temperatures.shape)
print('dtype:')
print(temperatures.dtype)
print('size:')
print(temperatures.size)
print(temperatures[0])
print(temperatures[1])


Shape:
(2, 7)
dtype:
float64
size:
14
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [ ]:
# ● Create a Pandas Series named marks with the following data:
# ➢ Marks: 95, 92, 89, 85, 80
# ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'
import pandas as pd
marks=pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [ ]:
# ● Use the integer index position to access the mark of the 1st rank student.
# ● Use the loc accessor to retrieve the marks of the top 3 ranks by
# specifying their index labels.
# ● Use the iloc accessor to retrieve the mark of the 3rd rank student.
# ● Apply a boolean mask to filter the Series and retrieve the ranks where the
# marks are greater than 90.
print(marks.iloc[0])

print(marks.loc[
    ['Rank1', 'Rank2', 'Rank3']
    ])
print(marks.iloc[2])

print(marks[marks > 90])


95
Rank1    95
Rank2    92
Rank3    89
dtype: int64
89
Rank1    95
Rank2    92
dtype: int64


In [ ]:
# ● Modify the mark of the student with the 1st rank to 100.
# ● Remove the entry corresponding to the last rank from the Series.
# ● Compute the CGPA by dividing each mark in the Series by 10.
print('1st rank to 100:')
marks.loc['Rank1'] = 100
print(marks)

marks = marks.drop('Rank5')
print(marks)


CGPA = marks / 10
print(CGPA)

1st rank to 100:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


In [ ]:
# ● Create a Pandas DataFrame named transactions with the following data:
# ➢ TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110
# ➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture',
# 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'
# ➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
# 'South', 'North'
# ➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400
import pandas as pd
transactions = pd.DataFrame({
   'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110] ,
   'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
   'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
   'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West',
   'South', 'North'],
   'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
print(transactions)



   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [ ]:
# ● Display the transactions DataFrame and its basic information, including
# head, tail, shape, column names, and data types.
# ● Display only the 'ProductCategory' and 'Amount' columns.
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
# ● Find the value counts for the 'ProductCategory' column.
# ● Find the unique values in the 'Region' column.
# ● Group by 'Region' and find the mean amount for each region.
print('HEAD:')
print(transactions.head())
print('TAIL:')
print(transactions.tail())
print('SHAPE:')
print(transactions.shape)
print('COLUMN NAMES:')
print(transactions.columns)
print('DATA TYPES:')
print(transactions.dtypes)
print('PRODUCT CATEGORY & AMOUNT:')
print(transactions[['ProductCategory','Amount']])
print('LAST 3 COLUMNS:')
print(transactions.iloc[:, -3:])
print('NORTH & AMOUNT > 200:')
print(transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
])
print('PRODUCT CATEGORY COUNTS:')
print(transactions['ProductCategory'].value_counts())
print('UNIQUE REGIONS:')
print(transactions['Region'].unique())
print('MEAN AMOUNT BY REGION:')
print(transactions.groupby('Region')['Amount'].mean())


HEAD:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
TAIL:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
SHAPE:
(10, 4)
COLUMN NAMES:
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
DATA TYPES:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
PRODUCT CATEGORY & AMOUNT:
  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothin

In [ ]:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.
# ● Remove the row with TransactionID 109.
# ● Delete the 'Discount' column from the DataFrame
print('TransactionID 102 to 165')
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165
print(transactions.loc[transactions['TransactionID'] == 102])
print('DISCOUNT COLUMN')
transactions['Discount']=transactions['Amount'] * 0.10
print(transactions)
print('Remove TransactionID 109:')
transactions = transactions[
    transactions['TransactionID'] != 109
]
print(transactions)
print('Delete the Discount Column:')
transactions = transactions.drop('Discount', axis=1)
print(transactions)

TransactionID 102 to 165
   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165
DISCOUNT COLUMN
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0
Remove TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Fu